network: projects/886724937990/global/networks/myvpc-ipv6
workerPoolSpecs:
    - machineSpec:
        machineType: g2-standard-4
        acceleratorType: NVIDIA_L4
        acceleratorCount: 1
      diskSpec:
        bootDiskType: pd-ssd
        bootDiskSizeGb: 200
      replicaCount: 1
      containerSpec:
        imageUri: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-training:kohya
      nfsMounts:
        - server: 10.7.48.2
          path: /vol2/working_dir
          mountPoint: /mnt/working_dir
        # - server: 10.150.39.10
        #   path: /mnt/vol1/models/Stable-diffusion
        #   mountPoint: /mnt/vol1/models