network: projects/PROJECT_NUMBER/global/networks/VPC_NETWORK_NAME
workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    acceleratorType: NVIDIA_TESLA_V100
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: us-central1-docker.pkg.dev/PROJECT_ID/ARTIFACT_REPOSITORY/sd-training:kohya
  nfsMounts:
    - server: NFS_IP_ADDRESS
      path: /vol1
      mountPoint: /mnt/nfs/model_repo