studySpec:
  metrics:
  - metricId: avr_loss
    goal: MINIMIZE
  parameters:
  - parameterId: lr
    scaleType: UNIT_LOG_SCALE
    doubleValueSpec:
      minValue: 0.00001
      maxValue: 0.0001
  measurementSelectionType: BEST_MEASUREMENT
trialJobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_V100
        acceleratorCount: 1
      replicaCount: 1
      containerSpec:
        imageUri: us-central1-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY_NAME/sd-training:kohya-hpo
        args: ["--method","kohya_lora","--model_name","CompVis/stable-diffusion-v1-4","--input_storage","/gcs/YOUR_BUCKET_NAME/IMAGE_FOLDER","--output_storage","/gcs/YOUR_BUCKET_NAME/OUTPUT_FOLDER","--display_name","PROMPT_NAME","--hpo","y"]
        command: ["python3","train_kohya.py"]
