pipelineName: kohya_lora
buildImage: False
NFS:
  enable: False
  server: 10.7.48.2
  path: /vol2
  mountPoint: /
gcpSpecs:
  project_number: 886724937990
  project_id: dave-selfstudy01
  region: us-central1
  pipeline_bucket: hzchen-iowa
vertexSpecs:
  network: projects/886724937990/global/networks/myvpc-ipv6
  workerPoolSpecs:
    machineSpec:
      machineType: n1-standard-4
      acceleratorType: NVIDIA_TESLA_T4
      acceleratorCount: 1
    replicaCount: 1
    containerSpec:
      imageUri: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-training:kohya_test
modelSpecs:
    method: kohya_lora
    model_name: runwayml/stable-diffusion-v1-5
    input_storage: /mnt/nfs/working_dir/img/
    output_storage: /mnt/nfs/working_dir/output/
    display_name: pipeline_test_lora
    lr: "0.0001"
    unet_lr: "0.00005"
    text_encoder_lr: "0.0001"
    lr_scheduler: cosine_with_restarts
    network_dim: "128"
    network_alpha: "64"
    batch_size: "1"
    save_every_n_epochs: "1"
    max_train_epochs: "10"
