studySpec:
  metrics:
  - metricId: loss
    goal: MINIMIZE
  parameters:
  - parameterId: lr
    scaleType: UNIT_LOG_SCALE
    doubleValueSpec:
      minValue: 0.00001
      maxValue: 0.0001
  measurementSelectionType: BEST_MEASUREMENT
trialJobSpec:
  workerPoolSpecs:
    - machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_TESLA_V100
        acceleratorCount: 1
      replicaCount: 1
      containerSpec:
        imageUri: us-central1-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY_NAME/sd-training:diffusers-hpo
        args: ["--method","diffuser_dreambooth","--model_name","runwayml/stable-diffusion-v1-5","--input_storage","/gcs/YOUR_BUCKET_NAME/FOLDER","--output_storage","/gcs/YOUR_BUCKET_NAME/FOLDER","--prompt","PROMPT","--class_prompt","CLASS PROMPT","--num_class_images","50","--max_train_steps","100","--text_encoder","True","--set_grads_to_none","True","--hpo","y"]
        command: ["python3","train.py"]