apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-train-service
  labels:
    app: stable-diffusion-train
spec:
  ports:
  - name: 7860-7860
    protocol: TCP
    port: 7860
    targetPort: 7860
  selector:
    app: stable-diffusion-train
  type: LoadBalancer